import {heroes,level,power,starCost} from './game.js';
import {illustration} from './revamp-ui.js';
export function levelPlan(s,id,count=1){
  if(!Number.isInteger(id)||!heroes[id]||!s.collection[id])throw Error('尚未拥有角色');
  if(!Number.isInteger(count)||count<1||count>5)throw Error('升级次数无效');
  const before=level(s,id),steps=Math.min(count,50-before);
  const cost=steps*(2*before+steps-1)*50;
  return {before,after:before+steps,steps,cost,gain:steps*5};
}
export function growthView(s,id){
 const h=heroes[id],lv=level(s,id),owned=!!s.collection[id],skill=s.skills[id]||0,stars=s.stars[id]||0,sc=starCost(s,id);
 const plan=owned?levelPlan(s,id,5):{before:lv,after:lv,cost:0,steps:0,gain:0};
 const one=owned?levelPlan(s,id):plan;
 const preview=structuredClone(s);preview.stars[id]=stars+1;preview.collection[id]=Math.max(1,(s.collection[id]||1)-sc.copies);
 const materials=(name,have,need)=>`<div class="core-material"><span>${name}</span><b class="${have<need?'short':''}">${have.toLocaleString()} / ${need.toLocaleString()}</b></div>`;
 return `<div class="core-growth"><div class="core-growth-top"><button data-close aria-label="返回英雄">‹</button><div><small>伙伴培养</small><h2>${h.name}</h2></div><b>${h.rarity} · ${h.role}</b></div><div class="core-growth-art">${illustration(h)}<div><span>Lv.${lv} / 50</span><strong>${power(s,id).toLocaleString()}</strong><small>当前战力</small></div></div><nav class="core-growth-tabs" aria-label="培养分类">${[['level','升级'],['skill','技能'],['star','突破']].map(([key,name])=>`<button data-growth-tab="${key}" aria-selected="${key==='level'}">${name}</button>`).join('')}</nav><div class="core-growth-body"><section data-growth-pane="level"><h3>等级提升</h3><div class="core-preview"><span>Lv.${lv}<small>当前</small></span><b>→</b><span>Lv.${plan.after}<small>连升 ${plan.steps} 级</small></span><em>战力 +${plan.gain}</em></div>${materials('金币',s.coins,plan.cost)}<div class="core-growth-actions"><button class="secondary" data-growth-level="1" ${!owned||!one.steps||s.coins<one.cost?'disabled':''}>升 1 级 · ${one.cost}</button><button class="primary" data-growth-level="5" ${!owned||!plan.steps||s.coins<plan.cost?'disabled':''}>升 ${plan.steps||5} 级 · ${plan.cost}</button></div><button class="secondary core-potion" data-exp-use ${!owned||!s.experience||lv>=50?'disabled':''}>使用药剂 · Lv.${lv} → ${Math.min(50,lv+2)}<small>剩余 ${s.experience} 瓶，消耗 1 瓶</small></button><button class="core-source" data-growth-source>缺资源？前往日常副本 ›</button></section><section data-growth-pane="skill" hidden><h3>${h.skill}</h3><p>${h.skillDescription}</p><div class="core-preview"><span>Lv.${skill+1}</span><b>→</b><span>Lv.${Math.min(6,skill+2)}</span><em>${skill>=5?'已满级':'技能强度 +6%'}</em></div>${materials('技能书',s.books,skill+1)}${materials('金币',s.coins,(skill+1)*200)}<button class="primary" data-skill-up ${!owned||skill>=5||s.books<skill+1||s.coins<(skill+1)*200?'disabled':''}>${skill>=5?'技能已满级':'提升技能'}</button><button class="core-source" data-growth-source>技能书来自日常副本 ›</button></section><section data-growth-pane="star" hidden><h3>星级突破</h3><div class="core-preview"><span>${stars} ★</span><b>→</b><span>${Math.min(5,stars+1)} ★</span><em>${stars>=5?'已满星':`战力 +${power(preview,id)-power(s,id)}`}</em></div>${materials('重复伙伴',Math.max(0,(s.collection[id]||0)-1),sc.copies)}${materials('金币',s.coins,sc.coins)}<p>三星解锁职业被动；突破保留当前等级和装备。</p><button class="primary" data-star ${!owned||stars>=5||s.collection[id]<=sc.copies||s.coins<sc.coins?'disabled':''}>${stars>=5?'已达五星':'确认突破'}</button><button class="core-source" data-growth-summon>重复伙伴来自召唤与碎片兑换 ›</button></section><details class="training-reset"><summary>培养重置 · 返还已记录资源</summary><p>保留星级与装备，旧版未记录的培养不会扣回。</p><button class="secondary" data-training-reset>查看返还预览</button></details>${owned?'<button class="secondary" data-growth-equipment>查看六部位装备 ›</button>':''}${owned?`<button class="secondary" data-profile-share>${s.supportHero===id?'✓ 已设为好友支援':'设为好友支援'}</button>`:''}<p class="profile-status" role="status"></p></div></div>`;
}
