import './style.css';
import {heroes,rarities,fresh,summon,power,enemyPower,battle,validSave} from './game.js';
const key='astral-cards-v1';let state=fresh(),tab='summon',results=[],report=null,notice='',storageWarning='';
try{const saved=JSON.parse(localStorage.getItem(key));if(validSave(saved))state=saved;}catch{storageWarning='浏览器存储不可用，进度可能无法保存。';}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageWarning='无法保存进度，请检查浏览器存储权限。';}}
const $=document.querySelector('#app');
function card(h,compact=false){return `<article class="card ${h.rarity} ${compact?'compact':''}" style="--accent:${rarities[h.rarity].color}"><span class="rarity">${h.rarity}</span><div class="portrait"><div class="halo"></div><span>${h.icon}</span></div><div class="card-info"><small>${h.title}</small><h3>${h.name}</h3><div class="stats">⚔ ${power(state,h.id)} <span>${state.collection[h.id]?`已拥有 ×${state.collection[h.id]}`:'未拥有'}</span></div></div></article>`;}
function render(){
 const total=Object.keys(state.collection).length;
 $.innerHTML=`<header><a class="brand" href="#"><span>✧</span> 星辉召唤 <small>ASTRAL CHRONICLES</small></a><div class="wallet">✦ <b>${state.gems.toLocaleString()}</b><span>星钻</span></div></header><main><div class="eyebrow">THE STARS ARE CALLING</div><div class="heading"><div><h1>让星光，成为你的力量。</h1><p>召唤命定的伙伴，踏上未知的冒险。</p></div><div class="progress"><b>${total}<span> / ${heroes.length}</span></b><small>已收集角色</small></div></div><nav>${[['summon','✧','星辉召唤'],['collection','▦','我的角色'],['adventure','⚔','冒险关卡']].map(([id,icon,label])=>`<button class="${tab===id?'active':''}" data-tab="${id}">${icon} ${label}</button>`).join('')}</nav>${storageWarning?`<p class="notice">${storageWarning}</p>`:''}${notice?`<p class="notice" role="status">${notice}</p>`:''}<section id="content">${tab==='summon'?summonView():tab==='collection'?collectionView():adventureView()}</section><footer>本地单人试玩 · 不含付费抽卡 · 进度自动保存</footer></main>`;
 $.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;notice='';render();});
 $.querySelectorAll('[data-pull]').forEach(b=>b.onclick=()=>{try{results=summon(state,+b.dataset.pull);notice=`召唤完成，获得 ${results.length} 位伙伴！`;save();}catch(e){notice=e.message+'，可通过挑战关卡获取星钻。';}render();});
 $.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{const id=+b.dataset.team;if(state.team.includes(id))state.team=state.team.filter(x=>x!==id);else if(state.team.length<3)state.team.push(id);else{notice='队伍最多 3 人，请先移除一位角色。';render();return;}notice='队伍已更新';save();render();});
 $.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{state.stage=+b.dataset.stage;report=null;save();render();});
 const fight=$.querySelector('#fight');if(fight)fight.onclick=()=>{try{report=battle(state);notice='';save();}catch(e){notice=e.message;}render();};
 const next=$.querySelector('#next');if(next)next.onclick=()=>{state.stage++;report=null;save();render();};
}
function summonView(){return `<div class="banner"><div class="banner-copy"><div class="pill">常驻召唤 · 星之祈愿</div><h2>穿越星海<br>与你相遇</h2><p>每一道光芒，都藏着一段新的故事。<br>召唤稀有伙伴，组建你的专属队伍。</p><div class="featured-label">UR · 月光祭司 露米</div></div><div class="banner-art"><div class="orbit one"></div><div class="orbit two"></div><div class="moon">☾</div><i class="spark s1">✧</i><i class="spark s2">✦</i><i class="spark s3">✧</i></div></div><div class="summon-controls"><div><h3>星辉召唤</h3><p>十连至少获得一位 SR 或更高角色</p></div><div class="pull-buttons"><button class="secondary" data-pull="1" ${state.gems<150?'disabled':''}>召唤 1 次 <span>✦ 150</span></button><button class="primary" data-pull="10" ${state.gems<1500?'disabled':''}>召唤 10 次 <span>✦ 1,500</span></button></div></div><div class="rates"><span>R <b>70%</b></span><span>SR <b>24%</b></span><span>SSR <b>5%</b></span><span>UR <b>1%</b></span><span class="pity">${state.pity} / 50 · 第 50 抽保底 SSR，SSR / UR 会重置计数</span></div>${results.length?`<h3 class="section-title">你的召唤结果 <small>重复角色自动提升战力，最多提升 10 次</small></h3><div class="cards results">${results.map(h=>card(h,true)).join('')}</div>`:`<h3 class="section-title">星海中的伙伴 <small>等待与你相遇</small></h3><div class="cards">${[heroes[0],heroes[3],heroes[5],heroes[8]].map(h=>card(h)).join('')}</div>`}`;}
function collectionView(){return `<div class="section-heading"><div><h2>我的角色</h2><p>点击角色加入或移出队伍，最多携带 3 位。</p></div><span class="pill">队伍 ${state.team.length} / 3 · 战力 ${state.team.reduce((n,id)=>n+power(state,id),0)}</span></div><div class="cards collection">${heroes.filter(h=>state.collection[h.id]).sort((a,b)=>power(state,b.id)-power(state,a.id)).map(h=>`<div>${card(h)}<button class="team-button ${state.team.includes(h.id)?'selected':''}" data-team="${h.id}">${state.team.includes(h.id)?'✓ 已上阵 · 点击移除':'+ 加入队伍'}</button></div>`).join('')}</div>`;}
function adventureView(){const strength=state.team.reduce((n,id)=>n+power(state,id),0);return `<div class="section-heading"><div><h2>星境远征</h2><p>首通获得 350 星钻，重复挑战获得 60 星钻。</p></div><span class="pill">已通关 ${state.cleared} / 12</span></div><div class="stages">${Array.from({length:12},(_,i)=>i+1).map(n=>`<button data-stage="${n}" class="stage ${state.stage===n?'current':''}" ${n>state.cleared+1?'disabled':''}><small>CHAPTER ${String(n).padStart(2,'0')}</small><b>${['萤火森林','月影古城','流沙秘境','霜雪之巅'][Math.floor((n-1)/3)]}</b><span>${n<=state.cleared?'✓ 已通关':n>state.cleared+1?'🔒 未解锁': '⚔ 等待挑战'}</span></button>`).join('')}</div><div class="battle-panel"><div><div class="eyebrow">CHAPTER ${state.stage}</div><h2>第 ${state.stage} 关 · 星境守卫</h2><p>队伍战力 <b>${strength}</b> / 敌方战力 <b>${enemyPower(state.stage)}</b></p><p>战斗为自动结算，伤害会在队伍战力的 90%–110% 之间波动。</p><div class="team-icons">${state.team.map(id=>`<span title="${heroes[id].name}">${heroes[id].icon} ${heroes[id].name}</span>`).join('')||'尚未选择角色'}</div></div><button id="fight" class="primary" ${!state.team.length?'disabled':''}>⚔ 开始挑战</button></div>${report?`<div class="battle-result ${report.won?'win':'loss'}" role="status"><h2>${report.won?'✦ 挑战成功！':'挑战失败'}</h2><p>造成 ${report.dealt} 点伤害 / 目标 ${report.target} 点。${report.won?`获得 ${report.reward} 星钻。`:'尝试召唤更强的伙伴，或通过重复挑战积攒星钻。'}</p>${report.won&&state.stage<12?'<button id="next" class="secondary">前往下一关 →</button>':''}${report.won&&state.stage===12?'<p>恭喜通关全部星境！你仍然可以继续收集角色。</p>':''}</div>`:''}`;}
render();
