import './style.css';
import {portrait} from './art.js';
import {heroes,rarities,fresh,summon,power,enemyPower,battle,validSave} from './game.js';
const key='astral-cards-v1';let state=fresh(),tab='summon',results=[],report=null,notice='',storageWarning='';
try{const saved=JSON.parse(localStorage.getItem(key));if(validSave(saved))state=saved;}catch{storageWarning='浏览器存储不可用，进度可能无法保存。';}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageWarning='无法保存进度，请检查浏览器存储权限。';}}
const $=document.querySelector('#app');
function card(h,compact=false){return `<article class="card ${h.rarity} ${compact?'compact':''}" style="--accent:${rarities[h.rarity].color}"><span class="rarity">${h.rarity}</span><span class="card-stars">${"✦".repeat({R:2,SR:3,SSR:4,UR:5}[h.rarity])}</span><div class="portrait">${portrait(h)}<div class="portrait-shine"></div></div><div class="card-info"><small>${h.title}</small><h3>${h.name}</h3><div class="stats">⚔ ${power(state,h.id)} <span>${state.collection[h.id]?`已拥有 ×${state.collection[h.id]}`:'未拥有'}</span></div></div></article>`;}
function render(){
 const total=Object.keys(state.collection).length;
 $.innerHTML=`<header><a class="brand" href="#"><span>✧</span> 星辉召唤 <small>ASTRAL CHRONICLES</small></a><button class="sound-toggle" id="sound-toggle" aria-label="切换音效">${soundOn?"♫ 音效开":"♪ 音效关"}</button><div class="wallet">✦ <b>${state.gems.toLocaleString()}</b><span>星钻</span></div></header><main><div class="eyebrow">THE STARS ARE CALLING</div><div class="heading"><div><h1>让星光，成为你的力量。</h1><p>召唤命定的伙伴，踏上未知的冒险。</p></div><div class="progress"><b>${total}<span> / ${heroes.length}</span></b><small>已收集角色</small></div></div><nav>${[['summon','✧','星辉召唤'],['collection','▦','我的角色'],['adventure','⚔','冒险关卡']].map(([id,icon,label])=>`<button class="${tab===id?'active':''}" data-tab="${id}">${icon} ${label}</button>`).join('')}</nav>${storageWarning?`<p class="notice">${storageWarning}</p>`:''}${notice?`<p class="notice" role="status">${notice}</p>`:''}<section id="content">${tab==='summon'?summonView():tab==='collection'?collectionView():adventureView()}</section><footer>✦ 星辉召唤 · 幻境纪元 <span>进度自动保存 · 无付费抽卡</span></footer></main>`;
 $.querySelector('#sound-toggle').onclick=()=>{soundOn=!soundOn;render();if(soundOn)tone(660,0.16);};
 $.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;notice='';render();});
 $.querySelectorAll('[data-pull]').forEach(b=>b.onclick=()=>{try{results=summon(state,+b.dataset.pull);notice=`召唤完成，获得 ${results.length} 位伙伴！`;save();render();showSummon(results);return;}catch(e){notice=e.message+'，可通过挑战关卡获取星钻。';}render();});
 $.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{const id=+b.dataset.team;if(state.team.includes(id))state.team=state.team.filter(x=>x!==id);else if(state.team.length<3)state.team.push(id);else{notice='队伍最多 3 人，请先移除一位角色。';render();return;}notice='队伍已更新';save();render();});
 $.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{state.stage=+b.dataset.stage;report=null;save();render();});
 const fight=$.querySelector('#fight');if(fight)fight.onclick=()=>{try{report=battle(state);notice='';save();render();showBattle(report);return;}catch(e){notice=e.message;}render();};
 const next=$.querySelector('#next');if(next)next.onclick=()=>{state.stage++;report=null;save();render();};
}
function summonView(){return `<div class="banner"><div class="banner-copy"><div class="pill">常驻召唤 · 星之祈愿</div><h2>穿越星海<br>与你相遇</h2><p>每一道光芒，都藏着一段新的故事。<br>召唤稀有伙伴，组建你的专属队伍。</p><div class="featured-label">UR · 月光祭司 露米</div></div><div class="banner-art">${portrait(heroes[0])}<div class="art-name">LUMI <span>月光的誓约</span></div></div><div class="banner-particles"><i style="--i:0"></i><i style="--i:1"></i><i style="--i:2"></i><i style="--i:3"></i><i style="--i:4"></i><i style="--i:5"></i><i style="--i:6"></i><i style="--i:7"></i><i style="--i:8"></i><i style="--i:9"></i><i style="--i:10"></i><i style="--i:11"></i><i style="--i:12"></i><i style="--i:13"></i><i style="--i:14"></i><i style="--i:15"></i></div></div><div class="summon-controls"><div><h3>星辉召唤</h3><p>十连至少获得一位 SR 或更高角色</p></div><div class="pull-buttons"><button class="secondary" data-pull="1" ${state.gems<150?'disabled':''}>召唤 1 次 <span>✦ 150</span></button><button class="primary" data-pull="10" ${state.gems<1500?'disabled':''}>召唤 10 次 <span>✦ 1,500</span></button></div></div><div class="rates"><span>R <b>70%</b></span><span>SR <b>24%</b></span><span>SSR <b>5%</b></span><span>UR <b>1%</b></span><span class="pity">${state.pity} / 50 · 第 50 抽保底 SSR，SSR / UR 会重置计数</span></div>${results.length?`<h3 class="section-title">你的召唤结果 <small>重复角色自动提升战力，最多提升 10 次</small></h3><div class="cards results">${results.map(h=>card(h,true)).join('')}</div>`:`<h3 class="section-title">星海中的伙伴 <small>等待与你相遇</small></h3><div class="cards">${[heroes[0],heroes[3],heroes[5],heroes[8]].map(h=>card(h)).join('')}</div>`}`;}
function collectionView(){return `<div class="section-heading"><div><h2>我的角色</h2><p>点击角色加入或移出队伍，最多携带 3 位。</p></div><span class="pill">队伍 ${state.team.length} / 3 · 战力 ${state.team.reduce((n,id)=>n+power(state,id),0)}</span></div><div class="cards collection">${heroes.filter(h=>state.collection[h.id]).sort((a,b)=>power(state,b.id)-power(state,a.id)).map(h=>`<div>${card(h)}<button class="team-button ${state.team.includes(h.id)?'selected':''}" data-team="${h.id}">${state.team.includes(h.id)?'✓ 已上阵 · 点击移除':'+ 加入队伍'}</button></div>`).join('')}</div>`;}
function adventureView(){const strength=state.team.reduce((n,id)=>n+power(state,id),0);return `<div class="section-heading"><div><h2>星境远征</h2><p>首通获得 350 星钻，重复挑战获得 60 星钻。</p></div><span class="pill">已通关 ${state.cleared} / 12</span></div><div class="stages">${Array.from({length:12},(_,i)=>i+1).map(n=>`<button data-stage="${n}" class="stage ${state.stage===n?'current':''}" ${n>state.cleared+1?'disabled':''}><small>CHAPTER ${String(n).padStart(2,'0')}</small><b>${['萤火森林','月影古城','流沙秘境','霜雪之巅'][Math.floor((n-1)/3)]}</b><span>${n<=state.cleared?'✓ 已通关':n>state.cleared+1?'🔒 未解锁': '⚔ 等待挑战'}</span></button>`).join('')}</div><div class="battle-panel"><div><div class="eyebrow">CHAPTER ${state.stage}</div><h2>第 ${state.stage} 关 · 星境守卫</h2><p>队伍战力 <b>${strength}</b> / 敌方战力 <b>${enemyPower(state.stage)}</b></p><p>战斗为自动结算，伤害会在队伍战力的 90%–110% 之间波动。</p><div class="team-icons">${state.team.map(id=>`<span title="${heroes[id].name}">${portrait(heroes[id])}<b>${heroes[id].name}</b></span>`).join('')||'尚未选择角色'}</div></div><button id="fight" class="primary" ${!state.team.length?'disabled':''}>⚔ 开始挑战</button></div>${report?`<div class="battle-result ${report.won?'win':'loss'}" role="status"><h2>${report.won?'✦ 挑战成功！':'挑战失败'}</h2><p>造成 ${report.dealt} 点伤害 / 目标 ${report.target} 点。${report.won?`获得 ${report.reward} 星钻。`:'尝试召唤更强的伙伴，或通过重复挑战积攒星钻。'}</p>${report.won&&state.stage<12?'<button id="next" class="secondary">前往下一关 →</button>':''}${report.won&&state.stage===12?'<p>恭喜通关全部星境！你仍然可以继续收集角色。</p>':''}</div>`:''}`;}
let soundOn=false,audio;
function tone(freq,duration=.15){if(!soundOn)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.connect(gain);gain.connect(audio.destination);osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.08,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.start();osc.stop(audio.currentTime+duration);}catch{}}
function modal(content,label){const dialog=document.createElement('dialog');dialog.className='cinematic';dialog.setAttribute('aria-label',label);dialog.innerHTML=content;document.body.append(dialog);const timers=[];let closed=false;const end=()=>{if(closed)return;closed=true;timers.forEach(clearTimeout);dialog.close();dialog.remove();};dialog.addEventListener('cancel',e=>{e.preventDefault();end();});dialog.querySelector('[data-close]').onclick=end;dialog.showModal();const after=(fn,ms)=>timers.push(setTimeout(()=>{if(!closed)fn();},ms));return {dialog,after,end};}
function showSummon(pulls){const best=pulls.reduce((a,b)=>({R:0,SR:1,SSR:2,UR:3}[a.rarity]>{R:0,SR:1,SSR:2,UR:3}[b.rarity]?a:b));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const m=modal(`<div class="summon-cinema" style="--accent:${rarities[best.rarity].color}"><div class="cinema-heading"><small>STELLAR SUMMON</small><h2>星门已开启</h2><p>光芒之中，命运与你相遇</p></div><div class="summon-gate"><div class="gate-ring"></div><div class="gate-core">✧</div></div><div class="reveal-grid ${pulls.length===1?'single':''}">${pulls.map((h,i)=>`<button class="reveal-slot" data-reveal="${i}" aria-label="揭晓第 ${i+1} 张卡牌"><div class="card-back"><span>✧</span><small>ASTRAL</small></div><div class="card-front">${card(h,true)}</div></button>`).join('')}</div><div class="cinema-actions"><button class="secondary" data-all>全部揭晓</button><button class="primary" data-close>收下伙伴</button></div></div>`,'召唤结果');const reveal=i=>{const el=m.dialog.querySelector(`[data-reveal="${i}"]`);if(el.classList.contains('revealed'))return;el.classList.add('revealed');tone({R:440,SR:550,SSR:740,UR:880}[pulls[i].rarity],.24);};m.dialog.querySelectorAll('[data-reveal]').forEach(el=>el.onclick=()=>reveal(+el.dataset.reveal));m.dialog.querySelector('[data-all]').onclick=()=>pulls.forEach((_,i)=>reveal(i));pulls.forEach((_,i)=>m.after(()=>reveal(i),reduced?0:650+i*180));}
function showBattle(outcome){const team=state.team.map(id=>heroes[id]);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const m=modal(`<div class="battle-cinema"><div class="cinema-heading"><small>CHAPTER ${state.stage} · 星境远征</small><h2>命运交锋</h2></div><div class="combat-arena"><div class="combat-party">${team.map((h,i)=>`<div class="combat-hero" data-attacker="${i}">${portrait(h)}<b>${h.name}</b></div>`).join('')}</div><div class="combat-vs">VS</div><div class="combat-enemy">${portrait(heroes[1],true)}<b>星境守卫</b><div class="hp-track"><div class="hp-fill"></div></div><small class="hp-text">${outcome.target} / ${outcome.target}</small><div class="damage-number"></div></div><div class="slash"></div></div><p class="combat-log" role="status">伙伴们已做好准备……</p><div class="combat-outcome" hidden><h2>${outcome.won?'VICTORY':'DEFEAT'}</h2><p>${outcome.won?`星境突破 · 获得 ${outcome.reward} 星钻`:'未能突破守卫 · 强化伙伴，再次出发'}</p></div><button class="primary" data-close>返回冒险</button></div>`,'战斗演出');const hit=i=>{const damage=Math.round(outcome.dealt*(i+1)/team.length)-Math.round(outcome.dealt*i/team.length);const remaining=Math.max(0,outcome.target-Math.round(outcome.dealt*(i+1)/team.length));const el=m.dialog.querySelector(`[data-attacker="${i}"]`);el.classList.add('attacking');const enemy=m.dialog.querySelector('.combat-enemy');enemy.classList.remove('hit');void enemy.offsetWidth;enemy.classList.add('hit');const num=m.dialog.querySelector('.damage-number');num.textContent='−'+damage;num.classList.remove('pop');void num.offsetWidth;num.classList.add('pop');m.dialog.querySelector('.hp-fill').style.width=remaining/outcome.target*100+'%';m.dialog.querySelector('.hp-text').textContent=remaining+' / '+outcome.target;m.dialog.querySelector('.combat-log').textContent=team[i].name+'发动星辉一击，造成 '+damage+' 点伤害！';tone(180+i*80,.2);};team.forEach((_,i)=>m.after(()=>hit(i),reduced?0:500+i*650));m.after(()=>{m.dialog.querySelector('.combat-outcome').hidden=false;m.dialog.querySelector('.combat-outcome').classList.add(outcome.won?'victory':'defeat');m.dialog.querySelector('.combat-log').textContent=outcome.won?'所有伙伴凯旋归来。':'守卫依然屹立，新的力量正在等待你。';tone(outcome.won?880:160,.4);},reduced?0:600+team.length*650);}
render();
