import {chapterStories} from './weekly-ui.js';
import {heroes,level,power,teamPower,stageEnemies,chapters,maxStage,enemyPower,dailyTasks,idleReward} from './game.js';
import {sprite,monster} from './pixel.js';
import {gameIcon,elementBadge} from './hero-ui.js';
import {worldScene,teamStrip} from './world-ui.js';
import {illustration,rewardDots} from './revamp-ui.js';
import {growthGoals} from './journey.js';
import {utcDay,trialForDay,expeditionChoices,expeditionReward} from './odyssey.js';
const tag=(title,subtitle,icon='adventure')=>`<div class="r-page-title">${gameIcon(icon)}<div><h2>${title}</h2><p>${subtitle}</p></div></div>`;
export function rebootHome(s,drawer=''){
 const goal=growthGoals(s)[0],theme=trialForDay(),dots=rewardDots(s);
 const today=s.daily.day===utcDay()?s.daily:null,taskReady=!today?.signed||dailyTasks.some(t=>today&&!today.claimed.includes(t.id)&&today[t.key]>=t.goal);
 const areas=[{name:'旅团集会',scene:'cozy-west',label:'与朋友分享冒险',kind:'social'},{name:'冒险营地',scene:'expedition-camp',label:'下一段故事，从这里开始',kind:'adventure'},{name:'星灯工匠街',scene:'cozy-east',label:'寻找新伙伴，打造新装备',kind:'summon'}];
 return `<div class="r-home fullscreen-town"><div class="town-scroll" tabindex="0" aria-label="左右滑动浏览营地">${areas.map((a,i)=>`<section class="town-district" aria-label="${a.name}">${worldScene(a.scene)}<div class="r-area-title"><small>伙伴营地 · V6</small><h1>${a.name}</h1><p>${a.label}</p></div>${i===0?'<button class="scene-building arena" data-tab="arena">竞技切磋 ›</button>':''}${i===1?'<span class="camp-river" aria-hidden="true"></span><span class="camp-fire" aria-hidden="true"></span>':''}<div class="r-camp-party">${s.team.map((id,n)=>`<button aria-label="与${heroes[id].name}交谈" data-camp-hero="${id}" data-street-hero="${id}" style="--order:${n}">${sprite(heroes[id])}<small>${heroes[id].name}</small></button>`).join('')}</div><div class="r-destination"><button class="r-destination-main" ${i===1?'data-adventure-mode="expedition"':`data-tab="${a.kind}"`}><span>${gameIcon(i===0?'social':i===1?'adventure':'summon')}</span><div><small>${i===1?'每日变化 · 六场连续挑战':'今天也有新的相遇'}</small><b>${i===1?theme.name:i===0?'加入冒险旅团':'开启星门招募'}</b><em>${i===1?theme.hint:i===0?'公会 Boss · 好友支援 · 聊天':'心愿英雄 · 碎片兑换'}</em></div><strong>›</strong></button></div></section>`).join('')}</div><div class="r-home-tools town-side-tools">${[['welfare','gift','福利',dots.welfare],['mail','mail','邮箱',dots.mail],['daily','book','任务',taskReady],['idle','shield','挂机',idleReward(s).minutes>=60]].map(([id,icon,name,dot])=>`<button data-home-drawer="${id}">${gameIcon(icon)}<small>${name}</small>${dot?'<i></i>':''}</button>`).join('')}</div><div class="town-travel"><button data-town-step="-1" aria-label="上一街区">‹</button><div>${areas.map((a,i)=>`<button data-town-dot="${i}" class="${i===1?'active':''}" aria-label="${a.name}"></button>`).join('')}</div><button data-town-step="1" aria-label="下一街区">›</button></div><div class="r-home-bottom"><button class="r-goal" data-goal="0"><small>成长手册</small><span><b>${goal.title}</b><em>›</em></span><p>${goal.detail}</p></button><div class="r-home-actions"><button data-tab="collection" data-building-kind="formation">${gameIcon('collection')}<span>编队</span></button><button data-tab="adventure" class="primary"><span>继续主线</span><b>${Math.ceil(s.stage/3)}－${(s.stage-1)%3+1}</b>${gameIcon('adventure')}</button><button data-tab="collection" data-building-kind="forge">${gameIcon('robe')}<span>装备</span></button></div></div>${drawer}</div>`;
}
export function rebootSummon(s,panel='summon',currency='auto'){
 const o=s.odyssey,curr=currency==='auto'?(s.tickets>0?'tickets':'gems'):currency;
 const nav=`<div class="scene-tabs"><button data-summon-panel="summon" class="${panel==='summon'?'active':''}">星门招募</button><button data-summon-panel="wish" class="${panel==='wish'?'active':''}">心愿与兑换 <small>${o.shards}碎片</small></button></div>`;
 if(panel==='wish')return `<div class="r-wish">${nav}${tag('让期待有方向','选择最多三位心愿英雄；同稀有度出现时，50%概率来自心愿单','heart')}<div class="r-wish-summary"><span>心愿 ${o.wishlist.length}/3</span><b>英雄碎片 ${o.shards}</b><small>重复招募：R +1 · SR +3 · SSR +8 · UR +15</small></div><div class="r-wish-grid">${heroes.filter(h=>['SSR','UR'].includes(h.rarity)).map(h=>`<article style="--rarity:${h.rarity==='UR'?'#be7a9c':'#bf9d5d'}"><button class="r-wish-pick ${o.wishlist.includes(h.id)?'chosen':''}" data-wish="${h.id}" aria-pressed="${o.wishlist.includes(h.id)}">${sprite(h)}<span>${h.name}</span><small>${h.rarity} · ${h.role}</small><i>${o.wishlist.includes(h.id)?'♥':'♡'}</i></button><button data-shard-recruit="${h.id}" ${o.shards<(h.rarity==='UR'?250:80)?'disabled':''}>${h.rarity==='UR'?250:80}碎片兑换</button></article>`).join('')}</div><p>普通抽卡稀有度概率与保底不变。碎片兑换直接获得指定英雄，不计入抽卡保底。</p></div>`;
 return `<div class="r-summon">${nav}<div class="r-summon-art">${illustration(heroes[0])}<div class="r-summon-caption"><small>常驻星门 · 全角色开放</small><h2>月光下的约定</h2><p>找到属于你的六人小队</p><button data-summon-panel="wish">${gameIcon('heart')}心愿单 ${o.wishlist.length}/3 ›</button></div><div class="r-summon-sprite">${sprite(heroes[0])}</div></div><div class="r-summon-controls"><div class="r-pity"><span>SSR 保底</span><b>${s.pity}<small>/50</small></b><progress value="${s.pity}" max="50"></progress><small>第50抽至少SSR · 十连至少SR</small></div><div class="r-currency"><button data-summon-currency="tickets" class="${curr==='tickets'?'active':''}">召唤券 <b>${s.tickets}</b></button><button data-summon-currency="gems" class="${curr==='gems'?'active':''}">星钻 <b>${s.gems}</b></button></div><div class="pull-buttons">${[1,10].map(n=>`<button class="${n===10?'primary':'secondary'}" ${curr==='tickets'?`data-ticket-pull="${n}"`:`data-pull="${n}"`} ${(curr==='tickets'?s.tickets<n:s.gems<n*150)?'disabled':''}><b>${n===10?'招募十次':'招募一次'}</b><small>${curr==='tickets'?`${n} 张召唤券`:`${n*150} 星钻`}${n===10?' · SR保底':''}</small></button>`).join('')}</div><details class="summon-rules"><summary>概率、保底与英雄说明</summary><p>R 70% · SR 24% · SSR 5% · UR 1%。SSR / UR 会重置50抽保底。十连不足SR时最后一抽补为SR。召唤券与星钻共用保底。</p></details></div></div>`;
}
export function expeditionView(s,nav){
 const r=s.odyssey.run,theme=trialForDay(),today=utcDay(),active=r?.active&&r.day===today,reward=expeditionReward(active?r.tier:1);
 return `<div class="r-expedition">${nav}${tag('遗迹远征',`${theme.name} · 每日早上8点变化`)}<div class="r-expedition-cover">${worldScene('battle-forest')}<div>${monster(2)}<h2>${theme.name}</h2><p>${theme.hint}</p><small>生命继承 · 随机祝福 · 每日一次结算奖励</small></div></div><div class="r-journey-route">${Array.from({length:6},(_,i)=>`<span class="${r?.day===today&&r.node>i?'complete':active&&r.node===i?'current':''}">${gameIcon(i===5?'arena':'adventure')}<small>${i===5?'首领':`战斗${i+1}`}</small></span>`).join('')}</div>${active?`<section class="r-expedition-state"><div class="r-party-health">${r.team.map(id=>`<span>${sprite(heroes[id])}<small>${heroes[id].name}</small><progress value="${r.hp[id]}" max="1000"></progress><em>${Math.round(r.hp[id]/10)}%</em></span>`).join('')}</div><div class="r-boon-list">${r.boons.map(id=>`<span>${{blade:'锋刃',vitality:'生命',spring:'泉水',guard:'守卫',crit:'鹰眼',rest:'休整'}[id]}</span>`).join('')||'<small>战斗胜利后选择本次远征祝福</small>'}</div>${r.pending?`<h3>选择一项祝福</h3><div class="r-boon-choices">${expeditionChoices(r).map(b=>`<button data-expedition-boon="${b.id}">${gameIcon(b.icon)}<b>${b.name}</b><small>${b.text}</small></button>`).join('')}</div>`:`<div class="v-route-choices">${[['trail','林间小路','标准战斗'],['elite','精英哨站','敌方+25% · 通关额外金币与碎片'],['spring','疗愈泉水','恢复15%生命 · 敌方+10%']].map(([id,name,hint])=>`<button data-expedition-route="${id}" class="${r.route===id?'selected':''}" ${r.route?'disabled':''}><b>${name}</b><small>${hint}</small></button>`).join('')}</div><button class="primary r-full-button" data-expedition-fight>挑战${r.node===5?'遗迹首领':`第 ${r.node+1} 场`}</button>`}<button class="r-abandon" data-expedition-abandon>放弃本次远征</button></section>`:`<section class="r-expedition-start"><h3>${r?.day===today&&r.claimed?'今日奖励已领取，可继续练习':'准备一场新的远征'}</h3><p>六场连续战斗，途中选择祝福。阵容在出发时锁定；失败可重新出发，次日轮换主题。</p><div class="r-tier-buttons">${[1,2,3].map(t=>`<button data-expedition-start="${t}" ${s.cleared<(t-1)*12?'disabled':''}><b>${['探索','挑战','大师'][t-1]}</b><small>${t===1?'开放':`通关${(t-1)*12}关开放`}</small></button>`).join('')}</div><div class="r-run-reward"><b>探索结算奖励</b><span>${reward.coins}金币 · ${reward.tickets}券 · ${reward.shards}碎片 · ${reward.stones}强化石</span><small>挑战 / 大师奖励为探索的2倍 / 3倍，所有难度共用每日领奖次数</small></div></section>`}</div>`;
}
export function rebootCampaign(s,nav,page,support=''){
 const chapter=page+1,foes=stageEnemies(s.stage),o=s.odyssey,claimed=o.milestones.includes(chapter);
 return `<div class="r-campaign">${nav}${tag('冒险手册',`已通关 ${s.cleared}/${maxStage} · 队伍战力 ${teamPower(s)}`)}<label class="r-chapter-select"><span>章节</span><select id="chapter-select">${chapters.map((name,i)=>`<option value="${i}" ${page===i?'selected':''} ${i*3>s.cleared?'disabled':''}>${i+1} · ${name}</option>`).join('')}</select></label><div class="r-chapter-map">${worldScene('battle-forest')}<h2>${chapters[page]}</h2><p class="v-chapter-story">${chapterStories[page]}</p><div class="r-stage-cards">${[page*3+1,page*3+2,page*3+3].map((stage,i)=>`<button data-stage="${stage}" class="${stage===s.stage?'selected':''}" ${stage>s.cleared+1?'disabled':''}>${monster(i)}<b>${i===2?'首领':'遭遇'} ${stage}</b><span>${'★'.repeat(o.stars[stage]||0)}${'☆'.repeat(3-(o.stars[stage]||0))}</span><small>${stage<=s.cleared?'再次挑战':stage>s.cleared+1?'尚未抵达':'继续冒险'}</small></button>`).join('')}</div></div><div class="r-chapter-reward"><div>${gameIcon('gift')}<span><b>章节收集奖励</b><small>2 张券 · 5 碎片 · ${500+chapter*100}金币</small></span></div><button class="${claimed?'secondary':'primary'}" data-chapter-reward="${chapter}" ${claimed||s.cleared<chapter*3?'disabled':''}>${claimed?'已领取':s.cleared<chapter*3?'通章领取':'领取'}</button></div><section class="r-battle-brief battle-panel"><div class="r-brief-heading"><div><small>${s.stage%3===0?'首领挑战':'主线遭遇'}</small><h2>第 ${s.stage} 关 · ${foes[0].name}</h2></div><b>${enemyPower(s.stage)}<small>敌方战力</small></b></div><div class="r-foe-strip">${foes.map(e=>`<span>${monster(e.kind||0)}<b>${e.name}</b><small>${e.element} · ${e.role}</small></span>`).join('')}</div><p>${foes[0].hint||'前排保护队友，利用属性克制与技能配合。'}</p>${teamStrip(s)}<button id="fight" class="primary r-full-button" ${!s.team.length?'disabled':''}>开始挑战</button><div class="r-stars-guide"><span>★ 通关</span><span>★ 全员存活</span><span>★ 8回合内</span></div>${o.stars[s.stage]>=3?`<div class="r-sweep"><small>三星扫荡 · 今日剩余 ${10-(o.sweep.day===utcDay()?o.sweep.count:0)} 次</small><button data-campaign-sweep="1">扫荡1次 · 50金币</button><button data-campaign-sweep="5">扫荡5次 · 250金币</button></div>`:''}</section><details class="r-more"><summary>精英、好友支援与战术信息</summary>${support}<button class="secondary" data-elite ${s.stage>s.cleared||!s.team.length?'disabled':''}>精英挑战 · 敌方战力×1.5</button><p>首通精英可获得150星钻、金币与装备。主线扫荡获取强化石和经验药剂，不增加抽卡资源。</p></details></div>`;
}
